# Generated by Django 2.0.4 on 2018-04-08 19:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180408_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='board',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=3, null=True), size=None), blank=True, null=True, size=None),
        ),
    ]
