# Generated by Django 2.0.6 on 2018-07-03 08:50

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180408_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='board',
            field=core.models.BoardField(base_field=core.models.BoardField(base_field=models.CharField(blank=True, max_length=3, null=True), size=None), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='game',
            name='game',
            field=models.CharField(choices=[('TicTacToe', 'Tic-tac-toe'), ('ConnectFour', 'Connect four')], max_length=16),
        ),
    ]
