# Generated by Django 2.0.7 on 2018-07-20 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_auto_20180703_0850'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=[
            migrations.CreateModel(
                name='GamePlayers',
                fields=[
                    ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ('order', models.PositiveSmallIntegerField(default=0)),
                ],
                options={
                    'db_table': 'core_game_players',
                },
            ),
            migrations.AlterField(
                model_name='game',
                name='players',
                field=models.ManyToManyField(through='core.GamePlayers', to=settings.AUTH_USER_MODEL),
            ),
            migrations.AddField(
                model_name='gameplayers',
                name='game',
                field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Game'),
            ),
            migrations.AddField(
                model_name='gameplayers',
                name='user',
                field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            ),
        ]),
        migrations.AddField(
            model_name='gameplayers',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
