# Generated by Django 3.0.6 on 2020-05-04 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180720_1808'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='gameplayers',
            table=None,
        ),
    ]
