# Generated by Django 6.0 on 2026-08-02 21:00

import core.games.registry
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_auto_20200504_0730"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gameplayers",
            options={"ordering": ("order",)},
        ),
        migrations.AddField(
            model_name="game",
            name="extra",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="game",
            name="winner",
            field=models.SmallIntegerField(
                blank=True,
                help_text="Index of the winning player. Null on a draw or unfinished game.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="game",
            field=models.CharField(
                choices=core.games.registry.game_choices, max_length=32
            ),
        ),
        migrations.AlterUniqueTogether(
            name="gameplayers",
            unique_together={("game", "order")},
        ),
        migrations.CreateModel(
            name="GameMove",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player", models.PositiveSmallIntegerField()),
                ("number", models.PositiveIntegerField()),
                ("move", models.JSONField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moves",
                        to="core.game",
                    ),
                ),
            ],
            options={
                "ordering": ("number",),
                "unique_together": {("game", "number")},
            },
        ),
    ]
